name: Flutter Build Test1

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Test1 works"
