name: Test Reusable1

on:
  workflow_dispatch:
  push:
    branches:
      - trae/agent-arUNOy
    paths:
      - ".github/trigger-reusable1.txt"

jobs:
  test:
    uses: ./.github/workflows/flutter-build-test1.yml
    with:
      upload-artifact: false
      upload-tag: "test"
